### ISSUE TITLE
status: 400 API KEY 인증 과정에서 에러가 발생하였습니다.

### ISSUE THREAD

**Issue by ghost** [cjh980402/kakao-link#1]
kakao.login(EMAIL, PASSWORD) 시 status: 400 오류가 발생합니다.

**Comment by cjh980402** [comment]
https://github.com/cjh980402/node-kakaolink/commit/8d29d8e8de8600e3ec2dcf362e0d4f376f94c71a 400 에러를 수정한 코드를 올렸습니다. 혹시 잘 작동하나요?

**Comment by ghost** [comment]
잘 됩니다!!!!! 사랑해요❤
